# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: DataSense
subtitle: xxxspy的博客
description: 专注于数据开发, 数据分析, 数据采集, python教学
author: xxxspy
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://mlln.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
- '*.json'
- '*.vender'
- '*.html'
- 'skip_render/**'
- '_posts/**/skip_render/**'
- '_posts/**/**.html'  # 这是用于 p5js教程
- 'siteMirrors/**'
- 'skip_me_*'


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY年MM月DD日
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
comment_per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
plugins:
  hexo-generator-baidu-sitemap
  hexo-generator-sitemap

baidusitemap:
  path: baidusitemap.xml
sitemap:
  path: sitemap.xml

## Themes: https://hexo.io/themes/
theme: alpha-dust

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git 
  # repo: git@github.com:xxxspy/blog.git
  repo: https://github.com/xxxspy/blog.git
  branch: master

kramed:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true


# copy files
static_dir: siteMirrors

# 熊掌号
xiongzhang_default_image: '/xiongzhang.png'


archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date


alias:
  /2019/index.html: /archives/2019/index.html
  /2018/index.html: /archives/2018/index.html
  /2017/index.html: /archives/2017/index.html
  /2016/index.html: /archives/2016/index.html
  /2015/index.html: /archives/2015/index.html


toc:
  maxdepth: 4