# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: DataSense
subtitle: xxxspy的博客
description: 专注于数据开发, 数据分析, 数据采集, python教学
author: xxxspy
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://mlln.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
- '*.json'
- '*.vender'
- '*.html'
- '*.js'
- 'skip_render/**'
- '_posts/**/skip_render/**'
- '_posts/**/**.html'  # 这是用于 p5js教程
- 'siteMirrors/**'
- 'skip_me_*'
- '**/*.js'


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY年MM月DD日
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
comment_per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
plugins:
  hexo-generator-baidu-sitemap
  hexo-generator-sitemap

baidusitemap:
  path: baidusitemap.xml
sitemap:
  path: sitemap.xml

## Themes: https://hexo.io/themes/
theme: alpha-dust

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git 
  # repo: git@github.com:xxxspy/blog.git
  repo: https://github.com/xxxspy/blog.git
  branch: master

kramed:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true


# copy files
static_dir: siteMirrors

# 熊掌号
xiongzhang_default_image: '/xiongzhang.png'


archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date


alias:
  /2019/index.html: /archives/2019/index.html
  /2018/index.html: /archives/2018/index.html
  /2017/index.html: /archives/2017/index.html
  /2016/index.html: /archives/2016/index.html
  /2015/index.html: /archives/2015/index.html


toc:
  maxdepth: 4

alimama:
  - name: 问卷代填保证质量
    url: https://jupyter.cn/home/
  - name: 问卷代填保证质量
    url: https://item.taobao.com/item.htm?spm=2013.1.w4023-21724689242.4.76085e0a2k46Ky&id=601314051411
    
toplinks:
  - name: Meta分析辅导+代找数据
    url: /2024/11/12/Meta%E5%88%86%E6%9E%90%E4%BB%A3%E5%81%9A-%E4%BB%8E%E6%89%BE%E6%95%B0%E6%8D%AE%E5%88%B0%E5%87%BA%E6%8A%A5%E5%91%8A/
  - name: SPSS+AMOS数据分析案例教程-关于中介模
    url: /2022/05/17/SPSS-AMOS数据分析案例教程-关于中介模型/
  - name: SPSS视频教程内容目录和跳转链接
    url: /2020/10/31/SPSS视频教程内容目录和跳转链接/
  - name: R语言快速入门视频教程
    url: https://mlln.cn/2022/08/11/R%E8%AF%AD%E8%A8%80%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8%E7%BB%83%E4%B9%A0%E6%9D%90%E6%96%99/
  - name: Python智联招聘数据分析
    url: https://space.bilibili.com/383752637/channel/collectiondetail?sid=778283
  - name: LCA潜在类别分析和Mplus应用
    url: /2022/07/24/潜在类别分析入门/
  - name: Amos结构方程模型数据分析入门教程
    url: /2022/06/12/Amos结构方程数据分析案例教程/
  - name: 倒U关系回归分析中介效应和调节效应分析SPSS视频教程
    url: /2022/12/05/倒U关系回归分析中介效应和调节效应分析SPSS和R语言应用视频教程/
  - name: 统计咨询(图文问答)
    url: ./#xingqiu